# ============================================================
# Compare classifiers across feature sets
#
# Models:
#   1. Elastic Net
#   2. SVM
#   3. Random Forest
#
# Feature sets:
#   1. global_endmotif_256
#   2. regional_mds_167
#   3. bioanalyzer_10bp_length
#
# This script reads standardized outputs generated by:
#   02_run_svm_nested_cv.R
#   03_run_rf_nested_cv.R
#   04_run_elastic_net_nested_cv.R
#
# Usage:
#   Rscript scripts/07_classification/05_compare_classifiers.R
# ============================================================

suppressPackageStartupMessages({
  library(readr)
  library(dplyr)
  library(tidyr)
  library(stringr)
  library(ggplot2)
  library(forcats)
  library(scales)
})

# ============================================================
# 1. Paths
# ============================================================

out_dir <- "results/tables/classification/classifier_comparison"
fig_dir <- "results/figures/classification/classifier_comparison"

dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(fig_dir, recursive = TRUE, showWarnings = FALSE)

feature_sets <- c(
  "global_endmotif_256",
  "regional_mds_167",
  "bioanalyzer_10bp_length"
)

feature_labels <- c(
  global_endmotif_256 = "End motif frequency",
  regional_mds_167 = "Regional MDS",
  bioanalyzer_10bp_length = "Bioanalyzer length bins"
)

# ============================================================
# 2. Settings
# ============================================================

task_order <- c(
  "Healthy vs MS",
  "Healthy vs Relapse",
  "Healthy vs Remission",
  "NonRelapse vs Relapse",
  "Remission vs Relapse"
)

model_order <- c(
  "Elastic Net",
  "SVM",
  "Random Forest"
)

method_order <- c(
  "Elastic Net",
  "RFE",
  "RF importance",
  "Limma FDR<0.05",
  "Top50 Limma",
  "Top50 trend"
)

feature_order <- c(
  "End motif frequency",
  "Regional MDS",
  "Bioanalyzer length bins"
)

feature_colors <- c(
  "End motif frequency" = "#264653",
  "Regional MDS" = "#E9C46A",
  "Bioanalyzer length bins" = "#8ECAE6"
)

model_colors <- c(
  "Elastic Net" = "#1D3557",
  "SVM" = "#E76F51",
  "Random Forest" = "#2A9D8F"
)

method_colors <- c(
  "Elastic Net" = "#1D3557",
  "RFE" = "#264653",
  "RF importance" = "#2A9D8F",
  "Limma FDR<0.05" = "#E76F51",
  "Top50 Limma" = "#6A4C93",
  "Top50 trend" = "#E9C46A"
)

heatmap_colors <- c(
  "#d73027",
  "#fdae61",
  "#ffffbf",
  "#a6d96a",
  "#006837"
)

plot_font <- ""

# ============================================================
# 3. Helper functions
# ============================================================

save_plot <- function(plot_object, filename, width, height, dpi = 300) {

  ggsave(
    filename = file.path(fig_dir, paste0(filename, ".png")),
    plot = plot_object,
    width = width,
    height = height,
    units = "in",
    dpi = dpi,
    bg = "white"
  )

  ggsave(
    filename = file.path(fig_dir, paste0(filename, ".pdf")),
    plot = plot_object,
    width = width,
    height = height,
    units = "in",
    device = "pdf"
  )
}

read_model_summary <- function(model, feature_set) {

  feature_label <- feature_labels[[feature_set]]

  if (model == "Elastic Net") {
    path <- file.path(
      "results/tables/classification/elastic_net",
      feature_set,
      "elastic_net_results_summary.csv"
    )
  }

  if (model == "SVM") {
    path <- file.path(
      "results/tables/classification/svm",
      feature_set,
      "svm_5methods_results_summary.csv"
    )
  }

  if (model == "Random Forest") {
    path <- file.path(
      "results/tables/classification/random_forest",
      feature_set,
      "rf_5methods_results_summary.csv"
    )
  }

  if (!file.exists(path)) {
    warning("Missing summary file: ", path)
    return(NULL)
  }

  df <- read_csv(path, show_col_types = FALSE)

  if (!"Method" %in% colnames(df)) {
    df$Method <- model
  }

  if (model == "Elastic Net") {
    df$Method <- "Elastic Net"
  }

  required_cols <- c(
    "Task",
    "Method",
    "Pooled_AUC",
    "Fold_AUC_mean",
    "Fold_AUC_sd",
    "Accuracy_mean",
    "Balanced_Accuracy_mean",
    "Sensitivity_mean",
    "Specificity_mean",
    "PPV_mean",
    "NPV_mean",
    "F1_mean",
    "N_Selected_Features_mean"
  )

  for (cc in required_cols) {
    if (!cc %in% colnames(df)) {
      df[[cc]] <- NA_real_
    }
  }

  df %>%
    mutate(
      Model = model,
      Feature_Set_ID = feature_set,
      Feature_Set = feature_label,
      Classifier = paste(Model, Feature_Set, Method, sep = " | "),
      Classifier_short = case_when(
        Model == "Elastic Net" ~ paste("EN", Feature_Set),
        Model == "SVM" ~ paste("SVM", Feature_Set, Method, sep = " - "),
        Model == "Random Forest" ~ paste("RF", Feature_Set, Method, sep = " - "),
        TRUE ~ Classifier
      )
    ) %>%
    select(
      Model,
      Feature_Set_ID,
      Feature_Set,
      Method,
      Classifier,
      Classifier_short,
      all_of(required_cols)
    )
}

safe_scale <- function(x) {
  if (all(is.na(x)) || sd(x, na.rm = TRUE) == 0) {
    return(rep(0, length(x)))
  }
  as.numeric(scale(x))
}

format_region <- function(x) {
  ifelse(
    str_detect(x, "^regional_MDS_chr[^_]+_\\d+_\\d+$"),
    x %>%
      str_replace("^regional_MDS_", "") %>%
      str_replace("^(chr[^_]+)_(\\d+)_(\\d+)$", "\\1:\\2-\\3"),
    ifelse(
      str_detect(x, "^chr[^_]+_\\d+_\\d+$"),
      str_replace(x, "^(chr[^_]+)_(\\d+)_(\\d+)$", "\\1:\\2-\\3"),
      x
    )
  )
}

clean_feature_label <- function(feature, feature_set) {

  feature <- as.character(feature)

  if (feature_set == "Regional MDS") {
    feature <- str_replace(feature, "^regional_MDS_", "")
    return(format_region(feature))
  }

  if (feature_set == "Bioanalyzer length bins") {
    feature <- str_replace(feature, "^length_", "")
    feature <- str_replace(feature, "bp$", " bp")
    feature <- str_replace_all(feature, "_", "-")
    return(feature)
  }

  feature
}

# ============================================================
# 4. Read all model summaries
# ============================================================

comparison_df <- bind_rows(
  lapply(feature_sets, function(fs) read_model_summary("Elastic Net", fs)),
  lapply(feature_sets, function(fs) read_model_summary("SVM", fs)),
  lapply(feature_sets, function(fs) read_model_summary("Random Forest", fs))
) %>%
  mutate(
    Task = factor(Task, levels = task_order),
    Model = factor(Model, levels = model_order),
    Feature_Set = factor(Feature_Set, levels = feature_order),
    Method = factor(Method, levels = method_order)
  )

if (nrow(comparison_df) == 0) {
  stop("No classifier summary files were found.")
}

write_csv(
  comparison_df,
  file.path(out_dir, "all_classifier_results_combined.csv")
)

cat("\nRows per model and feature set:\n")
print(table(comparison_df$Model, comparison_df$Feature_Set))

# ============================================================
# 5. Ranked summary table
# ============================================================

ranked_summary <- comparison_df %>%
  mutate(
    rank_score =
      Pooled_AUC +
      Balanced_Accuracy_mean +
      Sensitivity_mean +
      Specificity_mean +
      F1_mean -
      Fold_AUC_sd
  ) %>%
  arrange(desc(rank_score)) %>%
  select(
    Task,
    Model,
    Feature_Set,
    Method,
    Classifier_short,
    Pooled_AUC,
    Fold_AUC_mean,
    Fold_AUC_sd,
    Accuracy_mean,
    Balanced_Accuracy_mean,
    Sensitivity_mean,
    Specificity_mean,
    PPV_mean,
    NPV_mean,
    F1_mean,
    N_Selected_Features_mean,
    rank_score
  )

write_csv(
  ranked_summary,
  file.path(out_dir, "ranked_classifier_summary.csv")
)

# ============================================================
# 6. AUC heatmap: all classifier-method combinations
# ============================================================

auc_heatmap_df <- comparison_df %>%
  filter(!is.na(Pooled_AUC)) %>%
  mutate(
    Classifier_short = fct_reorder(
      Classifier_short,
      Pooled_AUC,
      .fun = mean,
      .na_rm = TRUE
    )
  )

p_auc_heatmap <- ggplot(
  auc_heatmap_df,
  aes(x = Task, y = Classifier_short, fill = Pooled_AUC)
) +
  geom_tile(color = "white", linewidth = 0.4) +
  geom_text(aes(label = sprintf("%.3f", Pooled_AUC)), size = 2.7) +
  scale_fill_gradientn(
    colours = heatmap_colors,
    values = scales::rescale(c(0, 0.5, 0.75, 0.90, 1.00)),
    limits = c(0, 1),
    name = "Pooled AUC"
  ) +
  labs(
    title = "Classifier comparison by pooled AUC",
    subtitle = "Elastic Net, SVM, and Random Forest across three feature sets",
    x = "Classification task",
    y = "Classifier"
  ) +
  theme_bw(base_size = 13, base_family = plot_font) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.text.y = element_text(size = 7, color = "black"),
    panel.grid = element_blank(),
    plot.title = element_text(face = "bold", hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5, color = "grey35")
  )

save_plot(
  p_auc_heatmap,
  filename = "01_classifier_auc_heatmap",
  width = 11,
  height = 15
)

# ============================================================
# 7. Best AUC by model and feature set
# ============================================================

best_auc_df <- comparison_df %>%
  filter(!is.na(Pooled_AUC)) %>%
  group_by(Task, Model, Feature_Set) %>%
  arrange(desc(Pooled_AUC), desc(Balanced_Accuracy_mean), desc(F1_mean), .by_group = TRUE) %>%
  slice(1) %>%
  ungroup() %>%
  mutate(
    Classifier_group = paste(Model, Feature_Set, sep = " | ")
  )

write_csv(
  best_auc_df,
  file.path(out_dir, "best_auc_by_model_feature_table.csv")
)

p_best_auc_heatmap <- ggplot(
  best_auc_df,
  aes(x = Task, y = Classifier_group, fill = Pooled_AUC)
) +
  geom_tile(color = "white", linewidth = 0.5) +
  geom_text(
    aes(label = paste0(sprintf("%.3f", Pooled_AUC), "\n", Method)),
    size = 2.8
  ) +
  scale_fill_gradientn(
    colours = heatmap_colors,
    values = scales::rescale(c(0, 0.5, 0.75, 0.90, 1.00)),
    limits = c(0, 1),
    name = "Best AUC"
  ) +
  labs(
    title = "Best AUC within each model and feature set",
    subtitle = "Best method selected separately for each classification task",
    x = "Classification task",
    y = "Model and feature set"
  ) +
  theme_bw(base_size = 12, base_family = plot_font) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    panel.grid = element_blank(),
    plot.title = element_text(face = "bold", hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5, color = "grey35")
  )

save_plot(
  p_best_auc_heatmap,
  filename = "02_best_auc_by_model_feature_heatmap",
  width = 10,
  height = 8
)

# ============================================================
# 8. Metric boxplots
# ============================================================

metric_cols <- c(
  "Pooled_AUC",
  "Fold_AUC_mean",
  "Accuracy_mean",
  "Balanced_Accuracy_mean",
  "Sensitivity_mean",
  "Specificity_mean",
  "PPV_mean",
  "NPV_mean",
  "F1_mean"
)

metrics_long <- comparison_df %>%
  select(
    Task,
    Model,
    Feature_Set,
    Method,
    Classifier_short,
    all_of(metric_cols),
    N_Selected_Features_mean
  ) %>%
  pivot_longer(
    cols = all_of(metric_cols),
    names_to = "Metric",
    values_to = "Value"
  ) %>%
  mutate(
    Metric = recode(
      Metric,
      Pooled_AUC = "Pooled AUC",
      Fold_AUC_mean = "Fold AUC",
      Accuracy_mean = "Accuracy",
      Balanced_Accuracy_mean = "Balanced accuracy",
      Sensitivity_mean = "Sensitivity",
      Specificity_mean = "Specificity",
      PPV_mean = "PPV",
      NPV_mean = "NPV",
      F1_mean = "F1"
    )
  )

write_csv(
  metrics_long,
  file.path(out_dir, "classifier_metrics_long.csv")
)

p_metric_box <- ggplot(
  metrics_long,
  aes(
    x = interaction(Model, Feature_Set, sep = "\n"),
    y = Value,
    fill = Feature_Set
  )
) +
  geom_boxplot(
    alpha = 0.80,
    outlier.shape = NA,
    color = "grey10",
    linewidth = 0.4
  ) +
  geom_jitter(
    aes(shape = Model),
    width = 0.08,
    size = 1.2,
    alpha = 0.75,
    color = "grey35"
  ) +
  facet_wrap(~ Metric, ncol = 3) +
  scale_y_continuous(breaks = seq(0, 1, 0.25)) +
  coord_cartesian(ylim = c(0, 1)) +
  scale_fill_manual(values = feature_colors) +
  scale_shape_manual(
    values = c(
      "Elastic Net" = 16,
      "SVM" = 17,
      "Random Forest" = 15
    )
  ) +
  labs(
    title = "Distribution of classifier performance metrics",
    subtitle = "Each point is one task-method combination",
    x = "Model and feature set",
    y = "Metric value",
    fill = "Feature set",
    shape = "Model"
  ) +
  theme_bw(base_size = 12, base_family = plot_font) +
  theme(
    axis.text.x = element_text(angle = 35, hjust = 1),
    plot.title = element_text(face = "bold", hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5, color = "grey35"),
    legend.position = "bottom",
    strip.background = element_rect(fill = "grey92", color = "black"),
    strip.text = element_text(face = "bold"),
    panel.grid.minor = element_blank()
  )

save_plot(
  p_metric_box,
  filename = "03_classifier_metric_boxplots",
  width = 16,
  height = 12
)

# ============================================================
# 9. Selected feature count comparison
# ============================================================

feature_plot_df <- comparison_df %>%
  filter(!is.na(Pooled_AUC)) %>%
  group_by(Task, Model, Feature_Set) %>%
  arrange(desc(Pooled_AUC), desc(Balanced_Accuracy_mean), desc(F1_mean), .by_group = TRUE) %>%
  slice(1) %>%
  ungroup()

p_features <- ggplot(
  feature_plot_df,
  aes(x = Task, y = N_Selected_Features_mean, fill = Feature_Set)
) +
  geom_col(
    position = position_dodge(width = 0.8),
    width = 0.5,
    color = "black",
    linewidth = 0.25
  ) +
  facet_wrap(~ Model, ncol = 1, scales = "free_y") +
  scale_fill_manual(values = feature_colors) +
  labs(
    title = "Number of selected features in the best-performing classifier",
    subtitle = "Best method selected by pooled AUC for each model and feature set",
    x = "Classification task",
    y = "Mean selected features",
    fill = "Feature set"
  ) +
  theme_bw(base_size = 12, base_family = plot_font) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    plot.title = element_text(face = "bold", hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5, color = "grey35"),
    legend.position = "bottom",
    strip.background = element_rect(fill = "grey92", color = "black"),
    strip.text = element_text(face = "bold"),
    panel.grid.minor = element_blank()
  )

save_plot(
  p_features,
  filename = "04_selected_features_comparison",
  width = 10,
  height = 10
)

# ============================================================
# 10. Best classifier per task
# ============================================================

best_per_task <- comparison_df %>%
  filter(!is.na(Pooled_AUC)) %>%
  group_by(Task) %>%
  arrange(desc(Pooled_AUC), desc(Balanced_Accuracy_mean), desc(F1_mean), .by_group = TRUE) %>%
  slice(1) %>%
  ungroup() %>%
  select(
    Task,
    Model,
    Feature_Set,
    Method,
    Classifier_short,
    Pooled_AUC,
    Balanced_Accuracy_mean,
    Sensitivity_mean,
    Specificity_mean,
    F1_mean,
    N_Selected_Features_mean
  )

best_per_task_feature <- comparison_df %>%
  filter(!is.na(Pooled_AUC)) %>%
  group_by(Task, Feature_Set) %>%
  arrange(desc(Pooled_AUC), desc(Balanced_Accuracy_mean), desc(F1_mean), .by_group = TRUE) %>%
  slice(1) %>%
  ungroup() %>%
  select(
    Task,
    Feature_Set,
    Model,
    Method,
    Classifier_short,
    Pooled_AUC,
    Balanced_Accuracy_mean,
    Sensitivity_mean,
    Specificity_mean,
    F1_mean,
    N_Selected_Features_mean
  )

write_csv(
  best_per_task,
  file.path(out_dir, "best_classifier_per_task.csv")
)

write_csv(
  best_per_task_feature,
  file.path(out_dir, "best_classifier_per_task_and_feature_set.csv")
)

# ============================================================
# 11. Elastic Net vs best SVM vs best RF radar
# ============================================================

best_svm_df <- comparison_df %>%
  filter(Model == "SVM", !is.na(Pooled_AUC)) %>%
  group_by(Task, Feature_Set) %>%
  arrange(desc(Pooled_AUC), desc(Balanced_Accuracy_mean), desc(F1_mean), .by_group = TRUE) %>%
  slice(1) %>%
  ungroup() %>%
  mutate(Classifier_Final = "Best SVM")

best_rf_df <- comparison_df %>%
  filter(Model == "Random Forest", !is.na(Pooled_AUC)) %>%
  group_by(Task, Feature_Set) %>%
  arrange(desc(Pooled_AUC), desc(Balanced_Accuracy_mean), desc(F1_mean), .by_group = TRUE) %>%
  slice(1) %>%
  ungroup() %>%
  mutate(Classifier_Final = "Best Random Forest")

elastic_net_df <- comparison_df %>%
  filter(Model == "Elastic Net", !is.na(Pooled_AUC)) %>%
  mutate(Classifier_Final = "Elastic Net")

best_model_compare_df <- bind_rows(
  elastic_net_df,
  best_svm_df,
  best_rf_df
) %>%
  mutate(
    Classifier_Final = factor(
      Classifier_Final,
      levels = c("Elastic Net", "Best SVM", "Best Random Forest")
    )
  )

write_csv(
  best_model_compare_df,
  file.path(out_dir, "elastic_net_vs_best_svm_vs_best_rf_by_task_and_feature_set.csv")
)

radar_compare <- best_model_compare_df %>%
  select(
    Task,
    Feature_Set,
    Classifier_Final,
    Method,
    Pooled_AUC,
    Accuracy_mean,
    Balanced_Accuracy_mean,
    Sensitivity_mean,
    Specificity_mean,
    PPV_mean,
    NPV_mean,
    F1_mean
  ) %>%
  rename(
    AUC = Pooled_AUC,
    Accuracy = Accuracy_mean,
    Bal_accuracy = Balanced_Accuracy_mean,
    Sensitivity = Sensitivity_mean,
    Specificity = Specificity_mean,
    PPV = PPV_mean,
    NPV = NPV_mean,
    F1 = F1_mean
  ) %>%
  pivot_longer(
    cols = c(AUC, Accuracy, Bal_accuracy, F1, Sensitivity, Specificity, NPV, PPV),
    names_to = "Metric",
    values_to = "Score"
  ) %>%
  mutate(
    Metric = factor(
      Metric,
      levels = c(
        "Accuracy",
        "AUC",
        "Bal_accuracy",
        "F1",
        "Sensitivity",
        "Specificity",
        "NPV",
        "PPV"
      ),
      labels = c(
        "Accuracy",
        "AUC",
        "Bal. accuracy",
        "F1",
        "Sensitivity",
        "Specificity",
        "NPV",
        "PPV"
      )
    ),
    Metric_ID = as.numeric(Metric),
    Score = pmin(pmax(Score, 0), 1)
  )

metric_labels <- levels(radar_compare$Metric)
metric_breaks <- seq_along(metric_labels)
n_metrics <- length(metric_labels)

radar_compare_closed <- radar_compare %>%
  group_by(Task, Feature_Set, Classifier_Final) %>%
  arrange(Metric_ID, .by_group = TRUE) %>%
  group_modify(~ {
    first_row <- .x[1, ]
    first_row$Metric_ID <- n_metrics + 1
    bind_rows(.x, first_row)
  }) %>%
  ungroup()

classifier_colors <- c(
  "Elastic Net" = "#1D3557",
  "Best SVM" = "#E76F51",
  "Best Random Forest" = "#2A9D8F"
)

p_elnet_vs_svm_vs_rf_radar <- ggplot(
  radar_compare_closed,
  aes(
    x = Metric_ID,
    y = Score,
    group = Classifier_Final,
    colour = Classifier_Final,
    fill = Classifier_Final
  )
) +
  geom_polygon(alpha = 0.08, linewidth = 0.35) +
  geom_line(linewidth = 0.55) +
  geom_point(size = 1.8) +
  facet_grid(Feature_Set ~ Task) +
  coord_polar(start = 0, clip = "off") +
  scale_colour_manual(values = classifier_colors, drop = FALSE) +
  scale_fill_manual(values = classifier_colors, drop = FALSE) +
  scale_x_continuous(
    breaks = metric_breaks,
    labels = metric_labels,
    limits = c(1, n_metrics + 1)
  ) +
  scale_y_continuous(
    limits = c(0, 1),
    breaks = seq(0, 1, by = 0.25),
    labels = number_format(accuracy = 0.01),
    expand = expansion(mult = c(0, 0))
  ) +
  labs(
    title = "Elastic Net vs Best SVM vs Best Random Forest",
    subtitle = "Best SVM/RF method selected by pooled AUC within each task and feature set",
    x = NULL,
    y = "Performance score",
    colour = "Classifier",
    fill = "Classifier"
  ) +
  theme_minimal(base_size = 11, base_family = plot_font) +
  theme(
    plot.title = element_text(face = "bold", size = 15, colour = "#1D3557", hjust = 0.5),
    plot.subtitle = element_text(size = 10, colour = "grey35", hjust = 0.5),
    strip.background = element_rect(fill = "grey92", colour = "black", linewidth = 0.4),
    strip.text.x = element_text(face = "bold", size = 8.5, colour = "black"),
    strip.text.y = element_text(face = "bold", size = 9.5, colour = "black"),
    axis.text.x = element_text(size = 6.2, face = "bold", colour = "grey25"),
    axis.text.y = element_text(size = 5.8, colour = "grey40"),
    panel.grid.major = element_line(colour = "grey82", linewidth = 0.35),
    panel.grid.minor = element_blank(),
    legend.position = "bottom",
    legend.title = element_text(face = "bold"),
    legend.text = element_text(size = 9)
  ) +
  guides(fill = "none", colour = guide_legend(nrow = 1))

save_plot(
  p_elnet_vs_svm_vs_rf_radar,
  filename = "05_elastic_net_vs_best_svm_vs_best_rf_radar",
  width = 14,
  height = 10
)

# ============================================================
# 12. Final message
# ============================================================

cat("\n============================================================\n")
cat("Classifier comparison completed.\n")
cat("Tables saved in:\n")
cat(out_dir, "\n")
cat("Figures saved in:\n")
cat(fig_dir, "\n")
cat("============================================================\n")
